In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt

In [41]:
pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', 300)

# Data

In [66]:
df = pd.read_csv("../data/cleaned_jetblue_df.csv")

In [69]:
df.head()

,searchDate,searchDayOfWeek,route,flightDate,flightDayOfWeek,startingAirport,destinationAirport,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeRaw,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsDurationInSeconds,segmentsCabinCode,departureTime,arrivalTime,departureCategory,arrivalCategory,searchDateInt,flightDateInt,daysLeft,numStops
0,2022-04-16,Saturday,ATL|EWR,2022-04-17,Sunday,ATL,EWR,PT2H9M,0,False,False,True,171.16,198.6,7,762.0,2022-04-17T07:30:00.000-04:00,2022-04-17T09:39:00.000-04:00,EWR,ATL,JetBlueAirways,7740,coach,07:30:00,09:39:00,Morning,Morning,20220416,20220417,1,0
1,2022-04-16,Saturday,ATL|JFK,2022-04-17,Sunday,ATL,JFK,PT2H15M,0,False,False,True,171.16,198.6,7,762.0,2022-04-17T09:00:00.000-04:00,2022-04-17T11:15:00.000-04:00,JFK,ATL,JetBlueAirways,8100,coach,09:00:00,11:15:00,Morning,Noon,20220416,20220417,1,0
2,2022-04-16,Saturday,ATL|JFK,2022-04-17,Sunday,ATL,JFK,PT2H23M,0,False,False,True,171.16,198.6,7,762.0,2022-04-17T18:50:00.000-04:00,2022-04-17T21:13:00.000-04:00,JFK,ATL,JetBlueAirways,8580,coach,18:50:00,21:13:00,Afternoon,Evening,20220416,20220417,1,0
3,2022-04-16,Saturday,ATL|LGA,2022-04-17,Sunday,ATL,LGA,PT2H16M,0,False,False,True,171.16,198.6,2,762.0,2022-04-17T12:03:00.000-04:00,2022-04-17T14:19:00.000-04:00,LGA,ATL,JetBlueAirways,8160,coach,12:03:00,14:19:00,Noon,Noon,20220416,20220417,1,0
4,2022-04-16,Saturday,ATL|LGA,2022-04-17,Sunday,ATL,LGA,PT2H19M,0,False,False,True,171.16,198.6,7,762.0,2022-04-17T10:40:00.000-04:00,2022-04-17T12:59:00.000-04:00,LGA,ATL,JetBlueAirways,8340,coach,10:40:00,12:59:00,Morning,Noon,20220416,20220417,1,0

In [5]:
df.dtypes

searchDate                       object
searchDayOfWeek                  object
route                            object
flightDate                       object
flightDayOfWeek                  object
startingAirport                  object
destinationAirport               object
travelDuration                   object
elapsedDays                       int64
isBasicEconomy                     bool
isRefundable                       bool
isNonStop                          bool
baseFare                        float64
totalFare                       float64
seatsRemaining                    int64
totalTravelDistance             float64
segmentsDepartureTimeRaw         object
segmentsArrivalTimeRaw           object
segmentsArrivalAirportCode       object
segmentsDepartureAirportCode     object
segmentsAirlineName              object
segmentsDurationInSeconds        object
segmentsCabinCode                object
departureTime                    object
arrivalTime                      object
departureCategory                object
arrivalCategory                  object
searchDateInt                     int64
flightDateInt                     int64
daysLeft                          int64
numStops                          int64
dtype: object

In [8]:
sorted(df.columns)

['arrivalCategory',
 'arrivalTime',
 'baseFare',
 'daysLeft',
 'departureCategory',
 'departureTime',
 'destinationAirport',
 'elapsedDays',
 'flightDate',
 'flightDateInt',
 'flightDayOfWeek',
 'isBasicEconomy',
 'isNonStop',
 'isRefundable',
 'numStops',
 'route',
 'searchDate',
 'searchDateInt',
 'searchDayOfWeek',
 'seatsRemaining',
 'segmentsAirlineName',
 'segmentsArrivalAirportCode',
 'segmentsArrivalTimeRaw',
 'segmentsCabinCode',
 'segmentsDepartureAirportCode',
 'segmentsDepartureTimeRaw',
 'segmentsDurationInSeconds',
 'startingAirport',
 'totalFare',
 'totalTravelDistance',
 'travelDuration']

In [10]:
df["segmentsCabinCode"]

0          coach
1          coach
2          coach
3          coach
4          coach
           ...
3949466    coach
3949467    coach
3949468    coach
3949469    coach
3949470    coach
Name: segmentsCabinCode, Length: 3949471, dtype: object

In [68]:
one_hot_columns = [
    "arrivalCategory", #makes sense to include
    "departureCategory", #makes sense to include
    "destinationAirport", #makes sense to include
    "flightDayOfWeek", #makes sense to include
    "searchDayOfWeek", #makes sense to include
    "segmentsAirlineName", #makes sense to include
    "segmentsCabinCode" #makes sense to include
]

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[one_hot_columns])
encoded_dense = encoded.toarray()

encoded_df = pd.DataFrame(encoded_dense, columns=encoder.get_feature_names_out(one_hot_columns))

print(df.shape)
print(encoded_df.shape)

print(31+63-7)

(3949471, 31)
(3949471, 63)
87

In [72]:
df.size

122433601

Original cleaned_df column size = 31

31+63 = 90

87 - 7 =

In [16]:
df[one_hot_columns]

,arrivalCategory,departureCategory,destinationAirport,flightDayOfWeek,searchDayOfWeek,segmentsAirlineName,segmentsCabinCode
0,Morning,Morning,EWR,Sunday,Saturday,JetBlueAirways,coach
1,Noon,Morning,JFK,Sunday,Saturday,JetBlueAirways,coach
2,Evening,Afternoon,JFK,Sunday,Saturday,JetBlueAirways,coach
3,Noon,Noon,LGA,Sunday,Saturday,JetBlueAirways,coach
4,Noon,Morning,LGA,Sunday,Saturday,JetBlueAirways,coach
...,...,...,...,...,...,...,...
3949466,Evening,Noon,LGA,Saturday,Wednesday,JetBlueAirways,coach
3949467,Evening,Afternoon,LGA,Saturday,Wednesday,JetBlueAirways,coach
3949468,Afternoon,Noon,LGA,Saturday,Wednesday,JetBlueAirways,coach
3949469,Noon,Morning,LGA,Saturday,Wednesday,JetBlueAirways,coach
3949470,Evening,Afternoon,LGA,Saturday,Wednesday,JetBlueAirways,coach

In [61]:
encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[one_hot_columns])
encoded_dense = encoded.toarray()

encoded_df = pd.DataFrame(encoded_dense, columns=encoder.get_feature_names_out(one_hot_columns))

In [62]:
encoded_df.shape

(3949471, 63)

In [71]:
encoded_df.size

248816673

In [58]:
viewable_filter = [
    "searchDayOfWeek_Sunday",
    "searchDayOfWeek_Monday", 
    "searchDayOfWeek_Tuesday"
]

testing_df = encoded_df.copy()

unique_searchdays_encodings = testing_df.drop_duplicates(subset = viewable_filter).reset_index()

unique_searchdays_encodings[viewable_filter]

   searchDayOfWeek_Sunday  searchDayOfWeek_Monday  searchDayOfWeek_Tuesday
0                     0.0                     0.0                      0.0
1                     1.0                     0.0                      0.0
2                     0.0                     1.0                      0.0
3                     0.0                     0.0                      1.0

In [53]:
day_of_week_hierarchy_dict = {
    "Sunday":1,
    "Monday":2,
    "Tuesday":3, 
    "Wednesday":4, 
    "Thursday":5, 
    "Friday":6,
    "Saturday":7 
}

df["searchDayOfWeekHierarchyEncoded"] = df["searchDayOfWeek"].map(day_of_week_hierarchy_dict)
df["searchDayOfWeekSine"] = np.sin(2 * np.pi * df["searchDayOfWeekHierarchyEncoded"] / 7)
df["searchDayOfWeekCosinee"] = np.cos(2 * np.pi * df["searchDayOfWeekHierarchyEncoded"] / 7)

testing_df = df.copy()

unique_days_df = testing_df.drop_duplicates(subset="searchDayOfWeekHierarchyEncoded").reset_index()

viewable_filter = [
    "searchDayOfWeek", 
    "searchDayOfWeekHierarchyEncoded", 
    "searchDayOfWeekSine",
    "searchDayOfWeekCosinee"   
]

unique_days_df[viewable_filter]

,searchDayOfWeek,searchDayOfWeekHierarchyEncoded,searchDayOfWeekSine,searchDayOfWeekCosinee
0,Saturday,7,-2.449294e-16,1.000000
1,Sunday,1,7.818315e-01,0.623490
2,Monday,2,9.749279e-01,-0.222521
3,Tuesday,3,4.338837e-01,-0.900969
4,Wednesday,4,-4.338837e-01,-0.900969
5,Thursday,5,-9.749279e-01,-0.222521
6,Friday,6,-7.818315e-01,0.623490

In [ ]:
df[
    ["searchDayOfWeek", "searchDayOfWeekHierarchyEncoded", "searchDayOfWeekSine", "searchDayOfWeekCosinee"]
]

,searchDayOfWeek,searchDayOfWeekHierarchyEncoded,searchDayOfWeekSine,searchDayOfWeekCosinee
3949466,Wednesday,4,-0.433884,-0.900969
3949467,Wednesday,4,-0.433884,-0.900969
3949468,Wednesday,4,-0.433884,-0.900969
3949469,Wednesday,4,-0.433884,-0.900969
3949470,Wednesday,4,-0.433884,-0.900969

In [70]:
df.size

122433601

In [23]:
27+63

90

In [26]:
encoded_df.shape

(3949471, 63)

In [28]:
df.shape

(3949471, 31)

In [29]:
31 - 7 + 63

87

In [30]:
df["segmentsCabinCode"].value_counts()

segmentsCabinCode
coach                         2814460
coach||coach                  1128915
coach||coach||coach              5459
business                          573
coach||business                    32
business||business                 20
business||coach                    10
coach||coach||coach||coach          1
coach||business||coach              1
Name: count, dtype: int64

In [37]:
df["segmentsAirlineName"].value_counts()

segmentsAirlineName
JetBlueAirways                                    2815033
JetBlueAirways||JetBlueAirways                    1125381
JetBlueAirways||JetBlueAirways||JetBlueAirways       4618
CapeAir||JetBlueAirways                              1842
JetBlueAirways||CapeAir                              1353
AmericanAirlines||JetBlueAirways                      388
JetBlueAirways||CapeAir||CapeAir                      254
CapeAir||CapeAir||JetBlueAirways                      248
JetBlueAirways||JetBlueAirways||CapeAir               125
CapeAir||JetBlueAirways||JetBlueAirways               105
JetBlueAirways||SilverAirways||JetBlueAirways          80
JetBlueAirways||CapeAir||JetBlueAirways                30
JetBlueAirways||AmericanAirlines                       13
CapeAir||CapeAir||CapeAir||JetBlueAirways               1
Name: count, dtype: int64

In [42]:
arbitrary_smaller_flights_filter = [
    "CapeAir||CapeAir||CapeAir||JetBlueAirways",
    "JetBlueAirways||AmericanAirlines",
    "JetBlueAirways||CapeAir||JetBlueAirways",
    "JetBlueAirways||SilverAirways||JetBlueAirways"
]

isolated_columns = [
    "segmentsAirlineName", 
    "segmentsCabinCode", 
    "totalFare"
]

df[
    df["segmentsAirlineName"].isin(arbitrary_smaller_flights_filter)
][isolated_columns].sort_values(by="totalFare", ascending=True).head(300)

,segmentsAirlineName,segmentsCabinCode,totalFare
3492387,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,205.49
3492388,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,211.09
3517044,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,211.09
3568214,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,215.49
3636800,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,215.49
3542848,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,215.49
3592377,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,215.49
3636801,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,221.09
3592378,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,221.09
3568215,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,221.09
3542849,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,221.09
3662538,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,235.50
3684963,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,235.50
3706742,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,235.50
3311408,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,246.69
3632229,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,260.49
3355372,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,261.69
3374604,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,262.70
3244236,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,266.70
3217296,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,266.70
3904227,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,270.08
3793945,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,270.08
3910469,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,275.68
3333560,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,277.69
3267713,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,278.50
3291362,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,278.50
3314063,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,283.50
3636224,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,288.09
3311226,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,289.69
3814950,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,298.50
3903876,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,298.50
3029106,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,301.69
3571011,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,302.10
3333381,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,304.69
3374415,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,306.70
3119875,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,308.49
3217109,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,309.70
3244052,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,309.70
3926109,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,315.50
3835426,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,315.50
3639567,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,320.49
3216262,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,321.50
3373049,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,321.69
3355191,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,321.69
3353823,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,321.69
3265067,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,322.70
3288730,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,322.70
3709145,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,323.49
3594800,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,323.49
3773242,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,326.09
3858692,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,326.09
3239715,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,336.50
3287705,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,336.50
3264030,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,336.50
3731161,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,340.50
3639219,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,340.50
3929841,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,345.09
3236469,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,348.48
3212976,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,348.48
3288550,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,349.70
3264881,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,349.70
3858713,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,357.08
3608532,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,381.50
3519560,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,381.50
3584071,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,381.50
3870765,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,383.48
3824701,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,387.48
3910688,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,397.09
3793590,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,401.50
3858356,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,401.50
3881131,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,401.50
3772890,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,401.50
3910689,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,405.49
3946088,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,411.50
3628709,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,412.50
3752718,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,416.50
3545305,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,416.50
3570652,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,416.50
3687360,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,426.50
3664938,JetBlueAirways||SilverAirways||JetBlueAirways,coach||coach||coach,426.50
2246655,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,525.50
2246656,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,531.10
1752081,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,635.00
146993,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,696.00
146995,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,696.00
1875125,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,719.71
146977,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,727.35
1875127,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,728.11
143611,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,756.00
143613,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,756.00
143615,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,756.00
140223,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,786.75
140224,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,786.75
140225,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,786.75
116796,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,796.00
116799,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,796.00
116800,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,796.00
29614,CapeAir||CapeAir||CapeAir||JetBlueAirways,coach||coach||coach||coach,906.90
74553,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,936.51
116763,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,936.51
143578,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,936.51
26724,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,936.51
1376530,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,939.59
26725,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,942.11
74554,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,942.11
116764,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,942.11
143579,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,942.11
146970,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,1257.67
146969,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,1257.67
120146,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,1257.67
120145,JetBlueAirways||CapeAir||JetBlueAirways,coach||coach||coach,1257.67
370613,JetBlueAirways||AmericanAirlines,coach||coach,3406.43
370612,JetBlueAirways||AmericanAirlines,coach||coach,3406.43
1158807,JetBlueAirways||AmericanAirlines,coach||coach,3407.50
1211442,JetBlueAirways||AmericanAirlines,coach||coach,3407.50
370614,JetBlueAirways||AmericanAirlines,coach||coach,3407.50
578216,JetBlueAirways||AmericanAirlines,coach||coach,3418.25
578217,JetBlueAirways||AmericanAirlines,coach||coach,3418.25
672689,JetBlueAirways||AmericanAirlines,coach||coach,3418.25
672690,JetBlueAirways||AmericanAirlines,coach||coach,3419.33
672691,JetBlueAirways||AmericanAirlines,coach||coach,3419.33
578218,JetBlueAirways||AmericanAirlines,coach||coach,3419.33
1560785,JetBlueAirways||AmericanAirlines,coach||coach,3531.34
1756635,JetBlueAirways||AmericanAirlines,coach||coach,3531.34